-- Compatibility marker for the short-lived production dashboard/report RPC
-- hotfix. The hardened, access-controlled definitions are installed by
-- 20260726070823_report_aggregates.sql.
--
-- Keeping this version as a no-op preserves compatibility if production has
-- already recorded migration 0008, while also allowing clean local resets to
-- create the crm schema before any CRM objects are referenced.
